import React from "react";

const data = {
  en: {
    hero: {
      lightMode: "LİGHT MODE",
      darkMode: "DARK MODE",
      lang1: "TÜRKÇE",
      lang2: "'YEGEÇ",
      title: "Hi! 👋",
      text: "I’m Hakan. I’m a full-stack developer. I can craft solid and scalable frontend products. Let’s meet!",
      img: "./public/images/hero.png",
      img1: "./public/images/LinkedIn.svg",
      img2: "./public/images/github1.svg",
      darkImg1: "./public/images/linkedark.svg",
      darkImg2: "./public/images/github.svg",
    },
    skills: {
      title: "Skills",
      map: {
        icons: [
          "./public/images/js-logo 1.svg",
          "./public/images/react.svg",
          "./public/images/realredux.svg",
          "./public/images/node.svg",
          "./public/images/realvscode.svg",
          "./public/images/figma-logo 1.svg",
        ],
        text: ["JAVASCRIPT", "REACT", "REDUX", "NODE", "VS CODE", "FİGMA"],
      },
    },
    profile: {
      title: "Profile",
      basicTitle: "Basic Information",
      aboutTitle: "About Me",
      birthDate: "04.09.1997",
      birthDateText: "Date of Birth",
      location: "Istanbul",
      locationText: "Location",
      education: "Kocaeli Uni. Electrical Eng., 2023",
      educationText: "Education",
      role: "Frontend",
      roleText: "Preferred Role",
      aboutText:
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Veniamaut, odit laborum aliquam voluptatum nisi mollitia. Mnima accusamusratione soluta aperiam sit voluptate? Dicta quod deserunt quamtemporibus cumque magnam!",
    },
    projects: {
      title: "Projects",
      map: [
        {
          title: "Random Jokes",
          text: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Veniamaut, odit laborum aliquam voluptatum nisi mollitia.",
          icons: ["react", "vercel", "axios", "router"],
          github: "View on Github",
          githubLink: "",
          goApp: "Go to app ",
          img: "./public/images/Laptop-1.png",
          color: "bg-projects",
          dark: "dark:bg-projects1",
        },
        {
          title: "Are you bored?",
          text: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Veniam aut, odit laborum aliquam voluptatum nisi mollitia minima accusamus ratione soluta aperiam sit voluptate? Dicta quod deserunt quam temporibus cumque magnam!",
          icons: ["react", "vercel", "axios", "router"],
          github: "View on Github",
          githubLink: "",
          goApp: "Go to app",
          img: "./public/images/Laptop-2.png",
          color: "bg-rightproject",
          dark: "dark:bg-projects2",
        },
      ],
    },
    footer: {
      text: "Let’s work together on your next product.",
      linkText: ["Github", "Personel Blog", "Linkedin", "Email"],
      colors: [
        "text-blue1 ",
        "text-skillsTitle dark:text-white",
        "text-linked ",
        "text-span",
      ],
      links: [
        "https://github.com/hakan-ilhan",
        "",
        "https://www.linkedin.com/in/hakan-can-ilhan-86778025b/",
        "",
      ],
    },
  },
  tr: {
    hero: {
      lightMode: "GÜNDÜZ MODU",
      darkMode: "GECE MODU",
      lang1: "SWITCH TO ",
      lang2: "ENGLISH",
      title: "Merhaba! 👋",
      text: "Ben Hakan. Full Stack Web Developer'ım. Frontend alanında kendimi geliştiriyorum. Bilgilerim aşağıda...",
      img: "./public/images/hero.png",
      img1: "./public/images/LinkedIn.svg",
      img2: "./public/images/github1.svg",
      darkImg1: "./public/images/linkedark.svg",
      darkImg2: "./public/images/github.svg",
    },
    skills: {
      title: "Yeteneklerim",
      map: {
        icons: [
          "./public/images/js-logo 1.svg",
          "./public/images/react.svg",
          "./public/images/realredux.svg",
          "./public/images/node.svg",
          "./public/images/realvscode.svg",
          "./public/images/figma-logo 1.svg",
        ],
        text: ["JAVASCRIPT", "REACT", "REDUX", "NODE", "VS CODE", "FİGMA"],
      },
    },
    profile: {
      title: "Profil",
      basicTitle: "Bilgilerim",
      aboutTitle: "Hakkımda",
      birthDate: "04.09.1997",
      birthDateText: "Doğum Tarihi",
      location: "İstanbul",
      locationText: "İkamet",
      education: "Kocaeli Uni. Elektrik Müh., 2023",
      educationText: "Eğitim Durumu",
      role: "Frontend",
      roleText: "Tercih Ettiği Rol",
      aboutText:
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Veniamaut, odit laborum aliquam voluptatum nisi mollitia. Mnima accusamusratione soluta aperiam sit voluptate? Dicta quod deserunt quamtemporibus cumque magnam!",
    },
    projects: {
      title: "Projelerim",
      map: [
        {
          title: "Random Jokes",
          text: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Veniamaut, odit laborum aliquam voluptatum nisi mollitia.",
          icons: ["react", "vercel", "axios", "router"],
          github: "Github Adresim",
          githubLink: "",
          goApp: "Go to app",
          img: "./public/images/Laptop-1.png",
          color: "bg-projects",
          dark: "dark:bg-projects1",
        },
        {
          title: "Are you bored?",
          text: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Veniam aut, odit laborum aliquam voluptatum nisi mollitia minima accusamus ratione soluta aperiam sit voluptate? Dicta quod deserunt quam temporibus cumque magnam!",
          icons: ["react", "vercel", "axios", "router"],
          github: "Github Adresim",
          githubLink: "",
          goApp: "Go to app",
          img: "./public/images/Laptop-2.png",
          color: "bg-rightproject",
          dark: "dark:bg-projects2",
        },
      ],
    },
    footer: {
      text: "Sonraki projeniz için birlikte çalışalım.",
      linkText: ["Github", "Personel Blog", "Linkedin", "Email"],
      colors: [
        "text-blue1",
        "text-skillsTitle dark:text-white",
        "text-linked ",
        "text-span",
      ],
      links: [
        "https://github.com/hakan-ilhan",
        "",
        "https://www.linkedin.com/in/hakan-can-ilhan-86778025b/",
        "",
      ],
    },
  },
};
export default data;
